language: python
python:
  - "2.7"
before_install:
  - virtualenv ./pyenv --distribute
  - source ./pyenv/bin/activate
install:
  - python setup.py develop
  - pip install coveralls nose moto
script:
  - nosetests
  - coverage run --source=loadkit setup.py test
after_success:
  - coveralls
